### ISSUE TITLE
No such file

### ISSUE THREAD

**Issue by okwme** [SamSchott/maestral-dropbox#26] opened 2019-07-20 07:26 UTC
sync fails on a mackup file....

```
Downloading 3925/3935...
Traceback (most recent call last):
  File "/home/billy/.local/bin/maestral", line 11, in <module>
    sys.exit(main())
  File "/home/billy/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/billy/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/billy/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/billy/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/billy/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/billy/.local/lib/python3.6/site-packages/maestral/console_script.py", line 22, in sync
    m = Maestral()
  File "/home/billy/.local/lib/python3.6/site-packages/maestral/main.py", line 140, in __init__
    success = self.sync.get_remote_dropbox()
  File "/home/billy/.local/lib/python3.6/site-packages/maestral/monitor.py", line 201, in wrapper
    res = func(self, *args, **kwargs)
  File "/home/billy/.local/lib/python3.6/site-packages/maestral/monitor.py", line 893, in get_remote_dropbox
    success = self.apply_remote_changes(result, save_cursor)
  File "/home/billy/.local/lib/python3.6/site-packages/maestral/monitor.py", line 953, in apply_remote_changes
    success += [f.result()]
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/billy/.local/lib/python3.6/site-packages/maestral/monitor.py", line 201, in wrapper
    res = func(self, *args, **kwargs)
  File "/home/billy/.local/lib/python3.6/site-packages/maestral/monitor.py", line 1169, in _create_local_entry
    md = self.client.download(entry.path_display, local_path)
  File "/home/billy/.local/lib/python3.6/site-packages/maestral/client.py", line 317, in download
    os.mkdir(dst_path_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/home/billy/Dropbox/mackup/.config/libreoffice/4/user/extensions/bundled/registry/com.sun.star.comp.deployment.configuration.PackageRegistryBackend'
```

**Comment by SamSchott** [comment] 2019-07-20 17:17
@okwme, I tried reproducing this by syncing my own libreoffice config files and did not run into any problems. Can you tell me the exact file name which is causing the problems?

It seams like Maestral is trying to create a folder at a location which does not exist (yet). This typically should not happen since folders are always synced before files.

As written in the README  PyPI version does not currently support file / folder names with multiple periods, such as "com.sun.star.comp[...]", but the Github version already does. Nevertheless, Maestral tries to create folders on-demand when they are needed as a download destination.

Could you try updating Maestral from Github with `pip install --upgrade git+https://github.com/SamSchott/maestral-dropbox` and see if the issue persists?

**Comment by SamSchott** [comment] 2019-08-07 16:11
Closing due to lack of information.

**Closed by SamSchott** 2019-08-07 16:11 UTC
Labels: bug
