### ISSUE TITLE
First user experience

### ISSUE THREAD

**Issue by richardjharris** [SamSchott/maestral-dropbox#84] opened 2020-02-06 01:16 UTC
Just wanted to provide you a first user experience as it was quite surprising.

I run Ubuntu 19.10. I installed maestral via pip and had to install pyqt3 via apt because the python version refused to install. 

```
rjh@carbon:~$ python3 -m pip install --upgrade pyqt5
Collecting pyqt5
  Using cached https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-xead6b97/pyqt5/setup.py'
```

I then ran maestral gui and set it up, pointing it at my existing dropbox folder `/home/rjh/Dropbox`. It created a subdir inside called `Dropbox (Maestral)` with a copy of all my stuff, which would fill up my hard disk. So I used the GUI to 'Exit Maestral'. This didn't work so I had to kill the process manually.

I then ran `maestral set-dir /home/rjh/Dropbox`. This then resulted in all files in my local dropbox copy being deleted. Quite suprising as some of those files had not yet been synced (the official dropbox client now refused to work with ecryptfs). So I lost that data. My fault of course, but I did not expect the client to immediately delete all files from the directory.

My motivation for using maestral is because the official dropbox client no longer works on my machine (due to ecryptfs). So it may be useful to provide a guide for people so they can move their existing Dropbox folder to maestral without any problems.

**Comment by SamSchott** [comment] 2020-02-06 20:36
@richardjharris, I am sorry to hear about that. Maestral currently does not support using an existing Dropbox folder and deliberately chooses a different default folder name "Dropbox (Maestral)". This is because it would create multiple issues if  the official client is still syncing the Dropbox folder when Maestral is started.

Regarding the command `maestral set-dir`, this is indeed a misleading name. It moves an *existing* Maestral folder to a new location and overwrites that location if necessary and if confirmed by the user. I take your point and will rename the command to `maestral move-dir` in the next release.

Finally, the GUI does not currently support custom folder names. Demand for this has not been sufficient to justify the additional complexity, but I have considered it. Pull requests are welcome.

There is one way to keep using an existing folder and merge its contents with your Dropbox: before setting up Maestral, rename the folder which you want to use to "Dropbox (Maestral)". Then select its location during setup and choose to merge its contents with your Dropbox. A similar workflow will be possible with the CLI soon.

Apologies for the experience, I hope it has not put you off! Now that the user base is becoming larger, I increasingly encounter corner cases and workflows which I did not anticipate...

**Comment by richardjharris** [comment] 2020-02-06 20:51
Thanks, it's not a huge problem as I can symlink it, I just don't like directory names with spaces/punctutation as they are more cumbersome to deal with on the command line :)

**Comment by SamSchott** [comment] 2020-02-06 21:29
If you are not too fed up with the command, you can always rename your folder again using `maestral set-dir` :)

> I don't think the installer made it clear that the directory I was specifying was the parent directory

It should have. It says in the setup dialog: 'Maestral will create a new folder named "Dropbox (Maestral)" in the selected location.'

>  I also don't think maestral set-dir asked me to confirm anything!

This may be a bug, I will check. It definitely would be wrong to delete anything without user confirmation!

**Comment by SamSchott** [comment] 2020-03-27 17:33
Closing as the setup experience should have improved now. Command line dialogs have been clarified and the wiki has been updated.

**Closed by SamSchott** 2020-03-27 17:33 UTC
Labels: cli, enhancement, gui

**Comment by Roy-Orbison** [comment] 2020-11-27 01:25
[The relevant wiki page to preserve existing dropbox folders.](https://github.com/SamSchott/maestral/wiki/Initial-Setup)
