### ISSUE TITLE
file not synced

### ISSUE THREAD

**Issue by idnovic** [SamSchott/maestral-dropbox#12] opened 2019-06-24 12:02 UTC
So I created a luks encrypted file. maestral should see it as binary without file type extension.
I moved the file inside my dropbox folder but maestral does not sync it.

the file was 125mb big and I retested with a 50mb version.

Can I somehow see how this file looks to maestral?
Original dropbox was able to sync it.

You can create a similar file:

```
# dd if=/dev/zero bs=1M count=100 of=~/test.img
# cryptsetup --cipher aes-xts-plain64 --key-size 512 luksFormat ~/test.img
# cryptsetup luksOpen ~/test.img test
# mkdosfs /dev/mapper/test
# mount /dev/mapper/test /mnt
...
# umount /mnt
# cryptsetup luksClose test 
```

**Comment by idnovic** [comment] 2019-06-24 12:22
this is a better guide, you need to create this file in the similar file size as mine

https://elephly.net/posts/2013-10-01-dm-crypt.html

**Comment by SamSchott** [comment] 2019-06-24 15:11
The file size should not be a problem. Large files are split into 10 MB chunks for the upload. What is the file name? You can check if Maestral excludes it from syncing by running:

```python
from maestral import MaestralClient
client = MaestralClient()

local_path = '/path/to/file/in/local/dropbox/folder'
dbx_path = client .to_dbx_path(local_path)

client.is_excluded(dbx_path)
client.is_excluded_by_user(dbx_path)
```

Then you can try to upload it manually:

```python
client.upload(self, local_path, dbx_path)
```

What error messages do you get when doing this?

**Comment by idnovic** [comment] 2019-06-24 16:07
```
>>> client.is_excluded(dbx_path)
False
>>> client.is_excluded_by_user(dbx_path)
False
```

**Comment by idnovic** [comment] 2019-06-24 16:08
But I still have the problem from #13 even though I deleted the files inside the dropbox folder. How can I force a resync?

**Comment by idnovic** [comment] 2019-06-24 16:10
After my #13 problem is gone I can retest it. Maybe the file is not anymore in the database because I removed it because it did not work.

**Comment by idnovic** [comment] 2019-06-24 16:48
```
[idnovic@id-lappy ~]0$ python3
Python 3.7.3 (default, May 11 2019, 00:38:04) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from maestral import MaestralClient
>>> client = MaestralClient()
 > Loading access token...
 [OK]
 > MaestralClient is ready.
>>> 
>>> local_path = '/home/idnovic/Dropbox/Luks/tester'
>>> dbx_path = client .to_dbx_path(local_path)
>>> 
>>> client.is_excluded(dbx_path)
False
>>> client.is_excluded_by_user(dbx_path)
False
>>> 

```

**Comment by idnovic** [comment] 2019-06-24 16:48
maestral still does not sync the file

**Comment by SamSchott** [comment] 2019-06-24 16:52
Hm, have you also tried the manual upload `client.upload(local_path, dbx_path)`?

**Comment by idnovic** [comment] 2019-06-24 16:53
```
>>> client.upload(local_path, dbx_path)
tester:   0%|                                       | 0.00/52.4M [00:00<?, ?B/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/idnovic/.local/lib/python3.7/site-packages/maestral/client.py", line 586, in upload
    path=dbx_path, client_modified=mtime, **kwargs)
  File "/home/idnovic/.local/lib/python3.7/site-packages/dropbox/files.py", line 462, in __init__
    self.client_modified = client_modified
  File "/home/idnovic/.local/lib/python3.7/site-packages/dropbox/files.py", line 561, in client_modified
    val = self._client_modified_validator.validate(val)
  File "/home/idnovic/.local/lib/python3.7/site-packages/dropbox/stone_validators.py", line 609, in validate
    return self.validator.validate(val)
  File "/home/idnovic/.local/lib/python3.7/site-packages/dropbox/stone_validators.py", line 368, in validate
    % generic_type_name(val))
dropbox.stone_validators.ValidationError: expected timestamp, got float

```

**Comment by idnovic** [comment] 2019-06-24 16:58
maybe add a notification for failed files too. I like the notification for working files/folders

**Comment by SamSchott** [comment] 2019-06-24 17:27
Thanks, that was very helpful. Its not a problem with your file but a bug in the code that occurs only when the file is split into chunks: The time stamp which is passed to the CommitInfo was wrong.

**Comment by idnovic** [comment] 2019-06-24 17:38
I loaded the newest update but maestral does not sync the file. manual upload over terminal(python) worked this time. 

So the remaining error seems to be that maestral did not think the file is new

**Comment by idnovic** [comment] 2019-06-24 17:40
Test 1: add a new file tester2 while maestral is running=ok
Test 2: add a new file tester3 while maestral is not running and sync on next start=ok

**Comment by idnovic** [comment] 2019-06-24 17:41
Test 0: sync a previously failed file=failure, seems to not see it as new file

**Comment by SamSchott** [comment] 2019-06-24 19:04
Strange, the previously failed file should have been picked up as "new" when restarting Maestral. No revision entry is created unless the upload is successful. 

At least, the critical bug when uploading files > 10 MB has been fixed.

**Comment by SamSchott** [comment] 2019-06-24 19:05
I am slowly starting to realize that file syncing is indeed not an easy problem...

**Comment by idnovic** [comment] 2019-06-25 17:05
Maybe it should have been picked up but it did fail before your fixed the source code. Are you sure the file was "new" to maestral?

**Comment by SamSchott** [comment] 2019-06-25 20:11
No, I am not sure. And since the upload finally worked out, it is difficult to debug now. One could recreate a failed upload and then check the (local) revision of the file:
```python
client = MaestralClient()
dbx_path = client.to_dbx_path('/local/path')
rev = client.get_local_rev(dbx_path)
```
If `rev == None`, the file has not been indexed yet and will be recognized as new when pausing and resuming the sync or when restarting Maestral.

In the long term, I would like to introduce:

- An option to reindex the Dropbox folder by downloading all metadata and comparing it to the local file structure. This could be used when the revision index becomes corrupted. 
- An option to view sync issues combined with an alert (e.g., a red system try icon). It should list files that failed to sync due to unsupported file names, wrong file permissions, insufficient space, etc. This will require better exception handling in the first instance.

**Comment by SamSchott** [comment] 2019-06-25 20:17
Addendum: Dropbox API errors are already caught and trigger a notification but the related files are not listed anywhere. Local errors, such as insufficient file permissions, are not handled at all but just fail silently (at least, as far as the GUI is concerned).

**Comment by idnovic** [comment] 2019-06-28 11:04
So something new happend, I added one file to my dropbox folder to an subfolder which is on the "to sync list" and I was under the impression that maestral did not sync it because I did not get a notification of the new file. So I deleted to file and I got a notification of the removed file. I added it again, still no notification but maestral did upload it.

What is the expected behavior? I was expecting a notification but only got one for the same file after I deleted it again.

**Comment by SamSchott** [comment] 2019-06-29 19:00
@idnovic, this is expected behavior now. Commit 629d49228625943481be37ce1f307fd582146ba4 limits notifications to remote changes only, and only from synced folders - unless more than 99 files have changed.

**Comment by SamSchott** [comment] 2019-07-10 16:46
I'll close this for now since the original issue has been fixed. If you continue to have trouble with a file not syncing after a failed first attempt (e.g., network connection lost), feel free to open a new issue.

I am working on methods to check and rebuilt the revision index. But they are still in testing...

**Closed by SamSchott** 2019-07-10 16:46 UTC
